; LCDWIKI ES3C28P: ESP32-S3, 2,8" ILI9341V + FT6336 touch, USB-C rett i S3-en
[platformio]
src_dir = .

[env:es3c28p]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../libraries
lib_deps =
  lovyan03/LovyanGFX@^1.2.7
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
